# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20180426_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='thought',
            field=models.TextField(default='SOME STRING', max_length=1000),
        ),
    ]
