# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_thoughts_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='thought',
            field=models.TextField(max_length=1000),
        ),
    ]
