# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20180426_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='heading',
            field=models.CharField(default='ggg', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thoughts',
            name='linkedin',
            field=models.CharField(default='ggg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thoughts',
            name='name',
            field=models.CharField(default='fff', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thoughts',
            name='position',
            field=models.CharField(default='fff', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='thought',
            field=models.TextField(max_length=10000),
        ),
    ]
