# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20180426_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='cover_image',
            field=models.ImageField(default='few', upload_to='thought_cover/'),
            preserve_default=False,
        ),
    ]
