# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_thoughts_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/thought_cover/'),
        ),
    ]
