# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20180426_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='profile_image',
            field=models.ImageField(default='FF', upload_to='uploads/profile_image/'),
            preserve_default=False,
        ),
    ]
