# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_thoughts_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date',
            field=models.CharField(default='dd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thoughts',
            name='date',
            field=models.CharField(default='dd', max_length=100),
            preserve_default=False,
        ),
    ]
