# Generated by Django 2.2 on 2019-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_thoughts_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('challenge', models.CharField(max_length=250)),
                ('solution', models.CharField(max_length=250)),
                ('timeline', models.CharField(max_length=200)),
                ('case_image', models.ImageField(upload_to='uploads/case_image/')),
            ],
        ),
    ]
