# Generated by Django 2.2 on 2019-06-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_case_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_study',
            name='case_image',
        ),
    ]
