# Generated by Django 2.2 on 2019-06-19 10:21

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_remove_case_study_case_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_study',
            name='solution',
            field=djrichtextfield.models.RichTextField(max_length=250),
        ),
    ]
