# Generated by Django 2.2 on 2019-06-20 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_case_study_case_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_study',
            name='uploaded_date',
            field=models.CharField(default=datetime.datetime(2019, 6, 20, 13, 35, 49, 854527), max_length=100),
        ),
        migrations.AlterField(
            model_name='case_study',
            name='case_image',
            field=models.ImageField(help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/case_image/'),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='uploaded_date',
            field=models.CharField(default=datetime.datetime(2019, 6, 20, 13, 35, 49, 854527), max_length=100),
        ),
    ]
