# Generated by Django 2.2 on 2019-06-20 08:18

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_auto_20190620_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_study',
            name='solution',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='case_study',
            name='uploaded_date',
            field=models.CharField(default='20 June,2019', max_length=100),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='cover_image',
            field=models.ImageField(help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/thought_cover/'),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='favorite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='profile_image',
            field=models.ImageField(help_text='Note: Image resolution should be 107px x 107px', upload_to='uploads/profile_image/'),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='thought',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='uploaded_date',
            field=models.CharField(default='20 June,2019', max_length=100),
        ),
    ]
