# Generated by Django 2.2 on 2019-06-20 11:47

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_auto_20190620_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_study',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Testing', 'Testing')], default='Web', max_length=250),
        ),
        migrations.AlterField(
            model_name='case_study',
            name='challenge',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='linkedin',
            field=models.CharField(help_text='For eg: https://www.linkedin.com/in/prasanth-v-092725156/', max_length=100),
        ),
    ]
