# Generated by Django 2.2 on 2019-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_auto_20190620_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_study',
            name='screen1',
            field=models.ImageField(blank=True, help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/case_image/screenshots'),
        ),
        migrations.AddField(
            model_name='case_study',
            name='screen2',
            field=models.ImageField(blank=True, help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/case_image/screenshots'),
        ),
        migrations.AddField(
            model_name='case_study',
            name='screen3',
            field=models.ImageField(blank=True, help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/case_image/screenshots'),
        ),
        migrations.AddField(
            model_name='case_study',
            name='screen4',
            field=models.ImageField(blank=True, help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/case_image/screenshots'),
        ),
        migrations.AddField(
            model_name='case_study',
            name='screen5',
            field=models.ImageField(blank=True, help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/case_image/screenshots'),
        ),
        migrations.AlterField(
            model_name='case_study',
            name='uploaded_date',
            field=models.CharField(default='21 June,2019', max_length=100),
        ),
        migrations.AlterField(
            model_name='thoughts',
            name='uploaded_date',
            field=models.CharField(default='21 June,2019', max_length=100),
        ),
    ]
