# Generated by Django 2.2 on 2019-06-21 12:25

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_auto_20190621_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.CharField(default='21 June,2019', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', djrichtextfield.models.RichTextField(max_length=10000)),
                ('news_image', models.ImageField(help_text='Note: Image resolution should be 1200px x 800px', upload_to='uploads/news_image/')),
            ],
        ),
    ]
